# Generated by Django 5.1.7 on 2025-03-24 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('message_preview', models.BooleanField(default=True)),
                ('notification_sounds', models.BooleanField(default=True)),
                ('online_status', models.BooleanField(default=True)),
                ('read_receipts', models.BooleanField(default=True)),
                ('last_seen', models.BooleanField(default=True)),
                ('profile_visibility', models.CharField(choices=[('everyone', 'Everyone'), ('contacts', 'Contacts Only'), ('none', 'Nobody')], default='everyone', max_length=10)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
